module.exports.countries = [
  {
    key: "Mexico",
    name: "México",
    color: "white",
    similar: true,
    option: true,
    wd: true,
    early: true,
    underFivePneumonia: 75,
    tuberculosis: 22,
    medianAge: 27,
    hospitalBeds: 15,
    isolationa: '3/13/2020',
    isolationb: '3/23/2020',
    population:127576000,
    populationDensity:66.44,
    capitalDensity:57,
    hospitalBedsm: 1.38,
  },
  {
    key: "Brazil",
    name: "Brasil",
    color: "#0cff0c",
    similar: true,
    option: true,
    wd: false,
    early: false,
    teleport: 7,
    medianAge: 31,
    population:211050000,
    populationDensity:25.04,
    capitalDensity:0,
    hospitalBedsm: 2.2,
  },
  {
    key: "US",
    owdname: 'United States',
    name: "US",
    color: "red",
    similar: false,
    option: true,
    wd: false,
    early: false,
    teleport: 16,
    isolationa: '3/19/2020',
    medianAge: 37,
    population:329065000,
    populationDensity:35.60,
    capitalDensity:0,
    hospitalBedsm: 2.77,
  },
  {
    key: "Argentina",
    name: "Argentina",
    color: "red",
    similar: true,
    option: false,
    wd: true,
    early: true,
    isolationa: '3/12/2020',
    isolationb: '3/17/2020',
    isolationc: '3/20/2020',
    medianAge: 30,
    population:44781000,
    populationDensity:16.17,
    capitalDensity:0,
    hospitalBedsm: 5,
  },
  {
    key: "Australia",
    name: "Australia",
    color: "#ff66b3",
    similar: false,
    option: false,
    wd: true,
    early: true,
    teleport: 8,
    medianAge: 37,
    isolationa: '3/13/2020',
    population:25203000,
    populationDensity:3.20,
    capitalDensity:0,
    hospitalBedsm: 3.84,
  },
  {
    key: "Germany",
    name: "Alemania",
    color: "#10e0f7",
    similar: false,
    option: true,
    wd: false,
    early: false,
    teleport: 18,
    isolationa: '3/13/2020',
    medianAge: 45,
    population:83517000,
    populationDensity:237.01,
    capitalDensity:0,
    hospitalBedsm: 8,
  },
  {
    key: "Colombia",
    name: "Colombia",
    color: "#3b89cf",
    similar: true,
    option: false,
    wd: false,
    early: true,
    isolationa: '3/13/2020',
    medianAge: 30,
    population:50339000,
    populationDensity:44.22,
    capitalDensity:0,
    hospitalBedsm: 1.71,
  },
  {
    key: "Ecuador",
    name: "Ecuador",
    color: "#f54795",
    similar: true,
    option: true,
    wd: false,
    early: false,
    teleport: 1,
    isolationa: '3/13/2020',
    medianAge: 26,
    population:17374000,
    populationDensity:66.93,
    capitalDensity:0,
    hospitalBedsm: 1.5,
  },
  {
    key: "Italy",
    name: "Italia",
    color: "#b46dea",
    similar: false,
    option: true,
    wd: false,
    early: false,
    teleport: 26,
    hospitalBeds: 34,
    medianAge: 46,
    isolationa: '3/13/2020',
    inflectionb: '3/9/2020',
    population:60550000,
    populationDensity:205.85,
    capitalDensity:0,
    hospitalBedsm: 3.18,
  },
  {
    key: "Netherlands",
    name: "Países Bajos",
    color: "#95FFCC",
    similar: false,
    option: true,
    wd: false,
    early: false,
    teleport: 13,
    medianAge: 42,
    population:17097000,
    populationDensity:508.54,
    capitalDensity:0,
    hospitalBedsm: 3.32,
  },
  {
    key: "New Zealand",
    name: "Nueva Zelanda",
    color: "#7C6FFD",
    similar: false,
    option: false,
    wd: false,
    early: false,
    medianAge: 32,
    population:4783000,
    populationDensity:18.20,
    capitalDensity:0,
    hospitalBedsm: 2.61,
  },
  {
    key: "Paraguay",
    name: "Paraguay",
    color: "#8ad1dd",
    similar: true,
    option: false,
    wd: true,
    early: true,
    isolationa: '3/13/2020',
    medianAge: 25,
    population:7045000,
    populationDensity:17.14,
    capitalDensity:0,
    hospitalBedsm: 1.3,
  },
  {
    key: "Peru",
    name: "Perú",
    color: "#42d79b",
    similar: true,
    option: false,
    wd: true,
    early: true,
    teleport: 2,
    isolationa: '3/13/2020',
    medianAge: 27,
    population:32510000,
    populationDensity:25.12,
    capitalDensity:0,
    hospitalBedsm: 1.6,
  },
  {
    key: "Portugal",
    name: "Portugal",
    color: "#4e7cb5",
    similar: false,
    option: false,
    wd: true,
    early: false,
    teleport: 8,
    medianAge: 44,
    population:10226000,
    populationDensity:112.14,
    capitalDensity:0,
    hospitalBedsm: 3.39,
  },
  {
    key: "Singapore",
    name: "Singapur",
    color: "#7C6FFD",
    similar: false,
    option: false,
    wd: true,
    early: true,
    teleport: 12,
    isolationa: '3/13/2020',
    medianAge: 40,
    population:5804000,
    populationDensity:7915.73,
    capitalDensity:0,
    hospitalBedsm: 2.4,
  },
  {
    key: "Korea, South",
    owdname: "South Korea",
    name: "Korea del sur",
    color: "#E0B83B",
    similar: false,
    option: false,
    wd: true,
    early: false,
    teleport: 28,
    isolationa: '3/13/2020',
    medianAge: 41,
    population:51225000,
    populationDensity:527.96,
    capitalDensity:0,
    hospitalBedsm: 12.27,
  },
  {
    key: "Spain",
    name: "España",
    color: "#ffc301",
    similar: false,
    option: true,
    wd: false,
    early: false,
    teleport: 17,
    isolationa: '3/13/2020',
    medianAge: 43,
    population:46737000,
    populationDensity:93.10,
    capitalDensity:0,
    hospitalBedsm: 2.97,
  },
  {
    key: "United Kingdom",
    name: "Reino Unido",
    color: "#d6da20",
    similar: false,
    option: true,
    wd: false,
    early: false,
    teleport: 14,
    isolationa: '3/13/2020',
    medianAge: 40,
    population:67530000,
    populationDensity:272.89,
    capitalDensity:0,
    hospitalBedsm: 2.54,
  },
  {
    key: "Sweden",
    name: "Suecia",
    color: "#f76f00",
    similar: false,
    option: true,
    wd: false,
    early: false,
    teleport: 13,
    isolationa: '3/13/2020',
    medianAge: 41,
    population:10036000,
    populationDensity:24.71,
    capitalDensity:0,
    hospitalBedsm: 2.22,
  },
  {
    key: "Taiwan*",
    owdname: "Taiwan",
    name: "Taiwan",
    color: "#84e101",
    similar: false,
    option: false,
    wd: true,
    early: true,
    teleport: 1,
    isolationa: '3/13/2020',
    medianAge: 40,
    population:23774000,
    populationDensity:0,
    capitalDensity:0,
  },
  {
    key: "Uruguay",
    name: "Uruguay",
    color: "#7C6FFD",
    similar: false,
    option: false,
    wd: false,
    early: false,
    medianAge: 34,
    population:3462000,
    populationDensity:19.75,
    capitalDensity:0,
    hospitalBedsm: 2.8,
  },
  {
    key: "mx-centinela",
    name: "México :(",
    color: "yellow",
    similar: true,
    option: true,
    wd: true,
    early: true,
    population:127576000,
  },
]