module.exports.countries =  [
    {key: "Argentina",
    name: "Argentina",
    similar: true,
    option: false,
    wd: true,
    early:true,
    isolationa: '3/12/2020',
    isolationb: '3/17/2020',
    isolationb: '3/20/2020',
  },
    {key: "Brazil",
    name: "Brasil",
    color: "#0cff0c",
    similar: true,
    option: true,
    wd: false,
    early:false,
    // isolationb: '3/13/2020',
    // isolationa: '3/13/2020',
  },
    {key: "Colombia",
    name: "Colombia",
    similar: true,
    option: false,
    wd: false,
    early:true,
    isolationa: '3/13/2020'
  },
    {key: "Ecuador",
    name: "Ecuador",
    similar: true,
    option: false,
    wd: false,
    early:false,
    isolationa: '3/13/2020'
  },
    {key: "Peru",
    name: "Perú",
    similar: true,
    option: false,
    wd: true,
    early:true,
    isolationa: '3/13/2020'
  },
    {key: "Mexico",
    name: "México",
    similar: true,
    option: true,
    wd: true,
    early:true,
    isolationa: '3/13/2020',
    isolationb: '3/23/2020',
  },
    {key: "Italy",
    name: "Italia",
    similar: false,
    option: true,
    wd: false,
    early: false,
    isolationa: '3/13/2020',
    inflectionb: '3/9/2020'
  },
    {key: "Spain",
    name: "España",
    similar: false,
    option: true,
    wd: false,
    early: false,
    isolationa: '3/13/2020'
  },
    {key: "United Kingdom",
    name: "UK",
    similar: false,
    option: true,
    wd: false,
    early: false,
    isolationa: '3/13/2020'
  },
    {key: "Germany",
    name: "Alemania",
    similar: false,
    option: true,
    wd: false,
    early: false,
    isolationa: '3/13/2020'
  },
    {key: "Sweden",
    name: "Suecia",
    similar: false,
    option: true,
    wd: false,
    early: false,
    isolationa: '3/13/2020'
  },
  {key: "Taiwan*",
    name: "Taiwan",
    similar: false,
    option: false,
    wd: true,
    early: true,
    isolationa: '3/13/2020'
  },
  {key: "Paraguay",
    name: "Paraguay",
    similar: true,
    option: false,
    wd: true,
    early: true,
    isolationa: '3/13/2020'
  },
  {key: "Korea, South",
    name: "Korea del sur",
    similar: false,
    option: false,
    wd: true,
    early: false,
    isolationa: '3/13/2020'
  },
  {key: "Australia",
    name: "Australia",
    similar: false,
    option: false,
    wd: true,
    early: true,
    isolationa: '3/13/2020'
  },
  {key: "Singapore",
  name: "Singapur",
  similar: false,
  option: false,
  wd: true,
  early: true,
  isolationa: '3/13/2020'
  },
  {key: "Netherlands",
  name: "Países Bajos",
  similar: false,
  option: true,
  wd: false,
  early: false,
  // isolationa: '3/13/2020'
  },
  {key: "US",
  name: "US",
  similar: false,
  option: true,
  wd: false,
  early: false,
  isolationa: '3/19/2020'
  },
  
]