module.exports.countries =  [
    {key: "Argentina",
    name: "Argentina",
    color: "red",
    similar: true,
    option: false,
    wd: true,
    early:true,
    isolationa: '3/12/2020',
    isolationb: '3/17/2020',
    isolationc: '3/20/2020',
  },
    {key: "Brazil",
    name: "Brasil",
    color: "#0cff0c",
    similar: true,
    option: true,
    wd: false,
    early:false,
    teleport: 7,
    // isolationb: '3/13/2020',
    // isolationa: '3/13/2020',
  },
    {key: "Colombia",
    name: "Colombia",
    color: "#3b89cf",
    similar: true,
    option: false,
    wd: false,
    early:true,
    isolationa: '3/13/2020'
  },
    {key: "Ecuador",
    name: "Ecuador",
    color: "#f54795",
    similar: true,
    option: false,
    wd: false,
    early:false,
    teleport: 1,
    isolationa: '3/13/2020'
  },
    {key: "Peru",
    name: "Perú",
    color: "#42d79b",
    similar: true,
    option: false,
    wd: true,
    early:true,
    teleport: 2,
    isolationa: '3/13/2020'
  },
    {key: "Mexico",
    name: "México",
    color: "white",
    similar: true,
    option: true,
    wd: true,
    early:true,
    underFivePneumonia: 75,
    tuberculosis: 22,
    populationAge: 27,
    hospitalBeds: 15,
    isolationa: '3/13/2020',
    isolationb: '3/23/2020',
  },
    {key: "Italy",
    name: "Italia",
    color: "#b46dea",
    similar: false,
    option: true,
    wd: false,
    early: false,
    teleport: 26,
    hospitalBeds: 34,
    isolationa: '3/13/2020',
    inflectionb: '3/9/2020'
  },
    {key: "Spain",
    name: "España",
    color: "#ffc301",
    similar: false,
    option: true,
    wd: false,
    early: false,
    teleport: 17,
    isolationa: '3/13/2020'
  },
    {key: "United Kingdom",
    name: "UK",
    color: "#d6da20",
    similar: false,
    option: true,
    wd: false,
    early: false,
    teleport: 14,
    isolationa: '3/13/2020'
  },
    {key: "Germany",
    name: "Alemania",
    color: "#10e0f7",
    similar: false,
    option: true,
    wd: false,
    early: false,
    teleport: 18,
    isolationa: '3/13/2020'
  },
    {key: "Sweden",
    name: "Suecia",
    color: "#72ddd0",
    similar: false,
    option: true,
    wd: false,
    early: false,
    teleport: 13,
    isolationa: '3/13/2020'
  },
  {key: "Taiwan*",
    name: "Taiwan",
    color: "#84e101",
    similar: false,
    option: false,
    wd: true,
    early: true,
    teleport: 1,
    isolationa: '3/13/2020'
  },
  {key: "Paraguay",
    name: "Paraguay",
    color: "#8ad1dd",
    similar: true,
    option: false,
    wd: true,
    early: true,
    isolationa: '3/13/2020'
  },
  {key: "Korea, South",
    name: "Korea del sur",
    color: "#E0B83B",
    similar: false,
    option: false,
    wd: true,
    early: false,
    teleport: 28,
    isolationa: '3/13/2020'
  },
  {key: "Australia",
    name: "Australia",
    color: "#ff66b3",
    similar: false,
    option: false,
    wd: true,
    early: true,
    teleport: 8,
    isolationa: '3/13/2020'
  },
  {key: "Singapore",
  name: "Singapur",
  color: "#7C6FFD",
  similar: false,
  option: false,
  wd: true,
  early: true,
  teleport: 12,
  isolationa: '3/13/2020'
  },
  {key: "Netherlands",
  name: "Países Bajos",
  color: "#95FFCC",
  similar: false,
  option: true,
  wd: false,
  early: false,
  teleport: 13,
  // isolationa: '3/13/2020'
  },
  {key: "US",
  name: "US",
  color: "red",
  similar: false,
  option: true,
  wd: false,
  early: false,
  teleport: 16,
  isolationa: '3/19/2020'
  },
  
]